repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.265
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.2.0
  hooks:
    - id: mypy
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
      stages: ["push", "merge-commit", "manual"]
